import "./globals.css";
import { FetchProvider } from "./authprovider/AuthProvider";

export const metadata = {
  title: "Dua & Ruqyah | All Duas Collection",
  description: "Generated by IRD Foundation",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <FetchProvider>
        <body>{children}</body>
      </FetchProvider>
    </html>
  );
}
